# Generated by Django 5.2.12 on 2026-03-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_seed_dietary_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('L', 'L'), ('oz', 'oz'), ('lbs', 'lbs'), ('cups', 'cups'), ('tbsp', 'tbsp'), ('tsp', 'tsp'), ('pieces', 'pieces'), ('whole', 'whole'), ('slices', 'slices'), ('pinch', 'pinch'), ('bunch', 'bunch'), ('cans', 'cans'), ('boxes', 'boxes'), ('bags', 'bags'), ('jars', 'jars'), ('bottles', 'bottles'), ('cloves', 'cloves'), ('sprigs', 'sprigs'), ('leaves', 'leaves'), ('stalks', 'stalks'), ('heads', 'heads'), ('packages', 'packages')], default='pieces', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.FloatField(default=1.0),
        ),
    ]
