# Generated by Django 5.2.11 on 2026-02-16 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooked_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('used_inventory_only', models.BooleanField(default=True)),
                ('savings_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_history', to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cooked_at'],
                'indexes': [models.Index(fields=['user', '-cooked_at'], name='recipes_mea_user_id_fb83a5_idx')],
            },
        ),
    ]
