# Generated by Django 5.2.12 on 2026-03-14 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_rename_recipegenerationusage_table'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='recipegenerationusage',
            new_name='recipes_rec_user_id_e051ec_idx',
            old_name='users_recip_user_id_d61e8d_idx',
        ),
    ]
